/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BibleLine {
    'lineNumber': number;
  }
}

declare global {


  interface HTMLBibleLineElement extends Components.BibleLine, HTMLStencilElement {}
  var HTMLBibleLineElement: {
    prototype: HTMLBibleLineElement;
    new (): HTMLBibleLineElement;
  };
  interface HTMLElementTagNameMap {
    'bible-line': HTMLBibleLineElement;
  }
}

declare namespace LocalJSX {
  interface BibleLine extends JSXBase.HTMLAttributes<HTMLBibleLineElement> {
    'lineNumber'?: number;
  }

  interface IntrinsicElements {
    'bible-line': BibleLine;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


