/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BibleLine {
    'lineNumber': number;
  }
  interface BibleVerse {
    'book': string;
    'chapter': string;
    'verses'?: string;
  }
}

declare global {


  interface HTMLBibleLineElement extends Components.BibleLine, HTMLStencilElement {}
  var HTMLBibleLineElement: {
    prototype: HTMLBibleLineElement;
    new (): HTMLBibleLineElement;
  };

  interface HTMLBibleVerseElement extends Components.BibleVerse, HTMLStencilElement {}
  var HTMLBibleVerseElement: {
    prototype: HTMLBibleVerseElement;
    new (): HTMLBibleVerseElement;
  };
  interface HTMLElementTagNameMap {
    'bible-line': HTMLBibleLineElement;
    'bible-verse': HTMLBibleVerseElement;
  }
}

declare namespace LocalJSX {
  interface BibleLine extends JSXBase.HTMLAttributes<HTMLBibleLineElement> {
    'lineNumber'?: number;
  }
  interface BibleVerse extends JSXBase.HTMLAttributes<HTMLBibleVerseElement> {
    'book'?: string;
    'chapter'?: string;
    'verses'?: string;
  }

  interface IntrinsicElements {
    'bible-line': BibleLine;
    'bible-verse': BibleVerse;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


